import {
  Bot,
  BrainCircuit,
  Brain,
  BarChart3,
  Users,
  TrendingUp,
  Server,
  Landmark,
  Target,
  Zap,
  Building,
  Building2,
  Headphones,
  Settings,
  FileText,
  Mic,
  LayoutDashboard,
  LineChart,
  PhoneCall,
  UserSearch,
  ClipboardCheck,
  CandlestickChart,
  Wallet,
  AppWindow,
  CloudCog,
  Lock,
  Scale,
  Map,
  GraduationCap,
  PenTool,
  Rocket,
  Banknote,
  HeartPulse,
  ShoppingCart,
  RadioTower,
  Truck,
  CreditCard,
  Factory,
  ShieldCheck,
  HardHat,
  Globe,
  Database,
  Shield,
  Sparkles,
  Languages,
  CalendarCheck,
  Headset,
  MessageCircle,
  type LucideIcon,
} from "lucide-react";

const ICONS: Record<string, LucideIcon> = {
  bot: Bot,
  "brain-circuit": BrainCircuit,
  brain: Brain,
  "bar-chart": BarChart3,
  users: Users,
  "trending-up": TrendingUp,
  server: Server,
  landmark: Landmark,
  target: Target,
  zap: Zap,
  building: Building,
  "building-2": Building2,
  headphones: Headphones,
  settings: Settings,
  "file-text": FileText,
  mic: Mic,
  "layout-dashboard": LayoutDashboard,
  "line-chart": LineChart,
  "phone-call": PhoneCall,
  "user-search": UserSearch,
  "clipboard-check": ClipboardCheck,
  "candlestick-chart": CandlestickChart,
  wallet: Wallet,
  "app-window": AppWindow,
  "cloud-cog": CloudCog,
  lock: Lock,
  scale: Scale,
  map: Map,
  "graduation-cap": GraduationCap,
  "pen-tool": PenTool,
  rocket: Rocket,
  banknote: Banknote,
  "heart-pulse": HeartPulse,
  "shopping-cart": ShoppingCart,
  "radio-tower": RadioTower,
  truck: Truck,
  "credit-card": CreditCard,
  factory: Factory,
  "shield-check": ShieldCheck,
  "hard-hat": HardHat,
  globe: Globe,
  database: Database,
  shield: Shield,
  languages: Languages,
  "calendar-check": CalendarCheck,
  headset: Headset,
  "message-circle": MessageCircle,
};

export function Icon({
  name,
  className,
  strokeWidth = 1.6,
}: {
  name: string;
  className?: string;
  strokeWidth?: number;
}) {
  const Cmp = ICONS[name] ?? Sparkles;
  return <Cmp className={className} strokeWidth={strokeWidth} aria-hidden="true" />;
}
